


# Permalinks
permalink:        pretty

# Setup
title:            SBT skeleton
tagline:          'Skeleton Scala project using sbt'
description:      'Skeleton project building multiple Scala versions for both JVM and Javascript with API documentation and executable tutorial'


baseurl: '/skelly/'


author:
  name:           'Neel Smith'


links:
  - title:  CITE Architecture home page
    url:  https://github.com/cite-architecture
    external: true
  - title:  Github repository for xcite
    url:  https://github.com/cite-architecture/xcite
    external: true
